### ISSUE TITLE
Stunfisk is a bit... compressed

### ISSUE THREAD

**Issue by thepeacemonk** [shigeyukey/Pokemanki-Gold#12]
![image](https://github.com/user-attachments/assets/7235eabd-3f69-4655-bd37-4c0ece95321c)

So, I noticed this specific Pokemon gif is... well... flat. I didn't notice this with other Pokemons.

Below is my debug for reference: 

```
Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.1-arm64-arm-64bit

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-10-09T23:36, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T04:15, 'None', '']
Pokemanki Gold - Raising Pokemon with Anki Customized by Shige ['1677779223', 2024-10-13T12:57, 'None', mod]
Review Heatmap ['1771074083', 2022-06-29T22:43, 'None', '']
The KING of Button Add-ons ['374005964', 2024-09-23T09:14, 'None', mod]

===IDs of active AnkiWeb add-ons===
1374772155 1677779223 1771074083 374005964 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by shigeyukey** [comment]
Thanks for reporting the problem.  I too thought this was odd but this is normal, the Stunfisk is very flat. I will try to find another Gif later.

**Comment by thepeacemonk** [comment]
Thank you shigey! Loving the add-on by the way, it really is carrying my studies lately, keep up with the great work, excited for your next addons!

I found some options in [here](https://pokemon.fandom.com/wiki/Stunfisk) where he kinda stands up so you can see him from another angle.

**Comment by shigeyukey** [comment]
Thanks! I changed the gif and updated the add-on.
