### ISSUE TITLE
AudioVisual Feedbackアドオンと競合する

### ISSUE THREAD

**Issue by Foxy-null** [shigeyukey/Pokemanki-Gold#2]
## バグの詳細
[Audivisual Feedback](https://ankiweb.net/shared/info/231569866)とPokemanki Goldを併用した際に、デッキ完了画面に表示されるはずの画像が読み込まれません。Audiovisual Feedbackに最初から入っていたテーマプリセットでも試してみましたが、同様の症状が見られたので、テーマプリセットが問題を引き起こしているわけではないみたいです。

## デバッグ情報
エラーは出ません。

## 再現方法
1. Ankiを開く
2. デッキ完了画面を表示する

## スクリーンショット
1. Pokemanki Goldが有効な状態
![Screenshot 2024-02-13 212115](https://github.com/shigeyukey/Pokemanki-Gold/assets/72304646/647eee63-1b20-4707-80b0-deea5b4c2f62)

2. Pokemanki Goldを無効にした状態
![anki_20240213_212507_559](https://github.com/shigeyukey/Pokemanki-Gold/assets/72304646/0841ae8d-1374-43a6-a9db-b53d3d78cde7)

## Environment
 - OS: `Windows 10 [22H2]`, `Windows 11 [23H2]`
 - Anki Version: `23.12.1`

**Comment by shigeyukey** [comment]
エラーの報告ありがとうございます､調整しました👍

**Comment by Foxy-null** [comment]
ありがとうございます！
