### ISSUE TITLE
[リクエスト] 博士からのお知らせをスクロール可能にする

### ISSUE THREAD

**Issue by Foxy-null** [shigeyukey/Pokemanki-Gold#4]
長い間統計を開いていないと、画面サイズをはみ出すほど長い通知が出てしまいます。
そこで、アラートウィンドウのログがある程度の高さ以上になる場合に、スクロール可能な形に切り替わるようにして頂きたいです。(画面高さの8割位)

- 旧
![image](https://github.com/shigeyukey/Pokemanki-Gold/assets/72304646/c7178add-d46c-4cca-b810-d618e2d904da)

- イメージ図（手書きですみません）
![image](https://github.com/shigeyukey/Pokemanki-Gold/assets/72304646/155e5ad7-b9cb-4a0d-b71b-221c888b591f)

ご検討よろしくお願いします。

**Comment by shigeyukey** [comment]
棒人間がおる(笑)了解です｡

あともしもご自分でこのPokemankiのコピーやカスタマイズ版を作りたい場合は自由にしてもらってOKです(他のAdd-onsも含め)｡
このPokemankiは統計からモンスターのレベルを計算する方法(つまり育成ゲームの作り方)とかを調べるのが主な目的なので､開発の優先順位はやや低めになってます｡

**Comment by shigeyukey** [comment]
修正してアップロードしました｡
