### ISSUE TITLE
Error message on latest update

### ISSUE THREAD

**Issue by jjp87** [shigeyukey/Pokemanki-Gold#5]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1677779223\custom_py\set_js_message.py", line 73, in open_pokemanki_trade
    mw.pokemenu.addAction(toggleaction)
AttributeError: 'AnkiQt' object has no attribute 'pokemenu'

**Comment by shigeyukey** [comment]
Thank you for the error report, I'll look into it.

**Comment by shigeyukey** [comment]
I repaired it and uploaded it to AnkiWeb.
