### ISSUE TITLE
Pokedex - Mr. Mime  - Page not Found.

### ISSUE THREAD

**Issue by 8bitpineapple** [shigeyukey/Pokemanki-Gold#7]
Clicking Mr. Mime's name doesn't redirect to the right page on Pokemon.com.

On their website URL's they omit full stops from names and replace spaces for -
i.e.
"Mr. Mime"  becomes "mr-mime"

**Comment by shigeyukey** [comment]
Thanks for reporting the issue, I will fix it in the next update.

**Comment by shigeyukey** [comment]
I fixed and updated it.
