### ISSUE TITLE
Pop up with each window change

### ISSUE THREAD

**Issue by Drkiwii** [shigeyukey/Pokemanki-Gold#8]
While I love the pokemon finally being displayed on the home screen, this pop-up now appears with every screen change (clicking on decks, browse, stats, etc), significantly lagging the program. I want to keep them displayed on the home menu, however the 5+ second delay when clicking on things while the pop-up tries to come up is not practical. It needs to be a boot-up-only pop-up and disabled until the next iteration of anki is opened.
![pokemanki](https://github.com/user-attachments/assets/6b3b6f83-8769-4e5d-b987-4bbea46517f6)

**Comment by shigeyukey** [comment]
Thanks for the feedback, I fixed and updated it.

* The recalculation will be triggered at these times.
    1. When finished the review.
    1.  When sync the decks (for reflecting the mobile data)

If the issue persists please contact me again.
